### ISSUE TITLE
soffice.bin为什么找不到

### ISSUE THREAD

**Issue by kinky2015** [ekoz/kbase-doc#1]
java.lang.IllegalStateException: invalid officeHome: it doesn't contain soffice.bin
org.artofsolving.jodconverter.office.DefaultOfficeManagerConfiguration.buildOfficeManager(DefaultOfficeManagerConfiguration.java:167) ~[jodconverter-core-3.0-beta-4.jar:na]
我已经安装了LibreOffice软件，也能在电脑上找到，我是在win10上安装的，请问有解决方案吗？

**Comment by kinky2015** [comment]
不好意思 是我自己粗心，问题已经自己解决。谢谢！

**Comment by qkmc-rk** [comment]
请问是什么问题怎么解决？
我的mac上明明有soffice.bin, 但java中就是提示找不到

**Comment by ekoz** [comment]
@qkmc-rk `office.home=D:/Program Files/LibreOffice` 配置文件里需要指定下，mac上的可以问下  @kinky2015

**Comment by qkmc-rk** [comment]
我的也解决了，MacOS下，只需要指定office根目录，不需要精确到bin目录或者program目录！

**Comment by ekoz** [comment]
#8

**Comment by 18810211910** [comment]
@qkmc-rk 咋解决的？office.home=/Applications/LibreOffice.app/Contents 配置之后 kbase-doc-alpha启动也是报错，根目录啥意思office.home=/Applications/LibreOffice.app这样也是报错
