### ISSUE TITLE
请问这个系统对doc、xls、ppt的格式是无法加水印吗？

### ISSUE THREAD

**Issue by chonggeisme** [ekoz/kbase-doc#12]
`com.eastrobot.doc.watermark.WatermarkException: Docx4JException

Caused by: org.docx4j.openpackaging.exceptions.Docx4JException: This file seems to be a binary doc/ppt/xls, not an encrypted OLE2 file containing a doc/pptx/xlsx`

另外，问下同学。我看代码，发现生成水印的方式（图片水印/文字水印），最后都是以图片的形式作为水印加到文档里的是吗

**Comment by ekoz** [comment]
@chonggeisme 支持07版本以后的格式，本质上是调用 docx4j 去加水印，文本水印是先转成图片实现的

**Comment by ekoz** [comment]
@chonggeisme 如果要对 doc ppt xls 加水印，我想到一个方案是用 LibreOffice 转成 07 后的版本，再调用加水印，不知是否可行，你可以尝试下

**Comment by chonggeisme** [comment]
> @chonggeisme 如果要对 doc ppt xls 加水印，我想到一个方案是用 LibreOffice 转成 07 后的版本，再调用加水印，不知是否可行，你可以尝试下

好的，谢谢您给出的意见。后面有时间我试试
