### ISSUE TITLE
我clone 过来的 pom.xml 和 你线上显示的是不一样的 这是为啥子呢

### ISSUE THREAD

**Issue by NickLoveHub** [ekoz/kbase-doc#13]
我clone 过来的 pom.xml 和 你线上显示的是不一样的 这是为啥子呢? 能不能顺便说下要怎么跑起来呢 :D

**Comment by ekoz** [comment]
@NickLoveHub 只有一个分支，so clone 过来的文件应该一致才对，先把 LibreOffice 跑起来，然后设置 `office` 相关配置，然后直接访问端口，应该就可以了

**Comment by NickLoveHub** [comment]
> @NickLoveHub 只有一个分支，so clone 过来的文件应该一致才对，先把 LibreOffice 跑起来，然后设置 `office` 相关配置，然后直接访问端口，应该就可以了
好的 我试试 谢谢
