### ISSUE TITLE
任重而道远

### ISSUE THREAD

**Issue by xiaofsu** [ekoz/kbase-doc#5]
**加油！**
目前还是没有很好的解决 -PPT的预览问题，
不过做出来提取文字已经蛮厉害了。

上传pdf文件时前端显示成功，但是后端报错。
`2019-04-23 14:40:52.355 ERROR 16872 --- [nio-8080-exec-8] com.eastrobot.web.IndexController        : failed conversion: pdf [1511384b] to html; org.artofsolving.jodconverter.office.OfficeException: unsupported conversion; input file: 1556001649210.pdf
`
![image](https://user-images.githubusercontent.com/46067472/56560021-df482f00-65d5-11e9-8673-667eb5905a77.png)

**Comment by ekoz** [comment]
@xiaofsu pdf 文件可以调用 pdf2dom 来实现转换 html，效果不佳，目前demo里未实现，只有测试用例。

**Comment by ekoz** [comment]
@xiaofsu ppt 的预览问题，可以将 ppt 转成 pdf，用 pdf.js 插件进行前端渲染，这个解决方案可以采用。

**Comment by xiaofsu** [comment]
谢谢，我正在尝试去使用。
