### ISSUE TITLE
启动不了：出现 invalid officeHome: it doesn't contain soffice.bin

### ISSUE THREAD

**Issue by R1310328554** [ekoz/kbase-doc#8]
启动springboot 的时候出现， java.lang.IllegalStateException: invalid officeHome: it doesn't contain soffice.bin: C:\Program Files\LibreOffice_6.3_SDK\sdk

请问是我的libreoffice的版本问题吗？

**Comment by ekoz** [comment]
@R1310328554 路径配置有误，配置到 LibreOffice 这层目录即可，安装文件清单：

![15751692568763](https://user-images.githubusercontent.com/3312512/69908712-dfd95b80-1429-11ea-8f06-ab3c2b37c8ba.png)

配置文件清单：
```
office.port=8100
office.home=D:/Program Files/LibreOffice
#office.home=D:/Program Files/OpenOffice
office.profile=
office.fileSizeMax=5242880
```

**Comment by szweemedlock** [comment]
macOS如何配置？
Applications/LibreOffice.app/Contents路径还是提示找不到soffice.bin

**Comment by R1310328554** [comment]
已经解决，需要安装LibreOffice； 而我安装的是 LibreOffice_sdk ...

**Comment by fage8** [comment]
> @R1310328554 路径配置有误，配置到 LibreOffice 这层目录即可，安装文件清单：
> 
> ![15751692568763](https://user-images.githubusercontent.com/3312512/69908712-dfd95b80-1429-11ea-8f06-ab3c2b37c8ba.png)
> 
> 配置文件清单：
> 
> ```
> office.port=8100
> office.home=D:/Program Files/LibreOffice
> #office.home=D:/Program Files/OpenOffice
> office.profile=
> office.fileSizeMax=5242880
> ```

我为啥在LibreOffice官网下载解压的和你的目录清单不一样，而且照样invalid officeHome: it doesn't contain soffice.bin

**Comment by fage8** [comment]
原来安装得是自定义安装，不然不对，可以正常运行，但是看不到上传的文件，都是一片空白呀

**Comment by bookc-man** [comment]
> Applications/LibreOffice.app/Contents路径还是提示找不到soffice.bin

[/Applications/LibreOffice.app/Contents](http://www.955yes.com/ask/108001226.html)

**Comment by startandend** [comment]
(base) MacBook-Pro:~ zhangmin$ # 确保有执行权限
(base) MacBook-Pro:~ zhangmin$ chmod +x /Applications/LibreOffice.app/Contents/MacOS/soffice

mac系统下，安装了LibreOffice之后，开放下执行权限
