### ISSUE TITLE
word文本水印，添加不上

### ISSUE THREAD

**Issue by dumplingbao** [ekoz/kbase-doc#9]
word文本水印，添加不上，也不报错，
图片水印可以

**Comment by dumplingbao** [comment]
文本可以添加水印，已添加的水印不能修改和删除

**Comment by ekoz** [comment]
@dumplingbao 上面的描述，我可以理解为图片水印和文本水印都ok了么？

**Comment by dumplingbao** [comment]
@ekoz 是的，感谢，目前不能删除水印，是吧

**Comment by ekoz** [comment]
@dumplingbao 嗯，暂未考虑删除水印的情况
